Yael Hasson, Kiara Villarroel, Paulina Salinas, Mariela Ubilla

In [3]:
import numpy as np

In [4]:
A = np.array([0, 1, 2, 3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [2]:
B = np.array([3, 2, 0, 1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [5]:
#multiplicación
A.dot(B)

array([[0, 1],
       [6, 7]])

In [6]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

básicamente, se dan vuelta las columnas y filas, quedando convertida el 0 y 1 que eran psrte de la fila 1 cpnveridos en la columna 1, lo mismo con la segunda fila que se cambia a columna

In [7]:
B.transpose()

array([[3, 0],
       [2, 1]])

es otra forma de efectuar la misma acción que la anteriormente ejecutada, que es cambiar el orden dimensional de una ndarray

In [4]:
arr=np.arange(15).reshape((3,5))

In [5]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

este es lo mismo pero una matriz más grande, es importante recordar que no se guarda encima del verdadero, por lo queal llamar al arr otra vez este sigue siendo el original

In [7]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [9]:
arr=np.random.randn(6,3)

se procede a generar un arreglo multidimensional con 6 filas y 3 columnas con datos aleatorios

In [10]:
arr

array([[ 0.20696438, -0.55460035,  1.32901814],
       [-1.31546587,  0.02442574, -0.2306903 ],
       [ 0.52739925, -0.64800158, -0.69670533],
       [-0.64255016, -0.44148198, -0.38922725],
       [ 1.21553153, -1.57265639, -1.0810801 ],
       [-0.6539582 ,  1.28005347, -0.04118134]])

In [11]:
arr.T

array([[ 0.20696438, -1.31546587,  0.52739925, -0.64255016,  1.21553153,
        -0.6539582 ],
       [-0.55460035,  0.02442574, -0.64800158, -0.44148198, -1.57265639,
         1.28005347],
       [ 1.32901814, -0.2306903 , -0.69670533, -0.38922725, -1.0810801 ,
        -0.04118134]])

y con el uso de  .T ya podemos efectuar la transposición de filas por columnas

In [12]:
np.dot(arr.T, arr)

array([[ 4.36948362, -2.95370987, -0.82597528],
       [-2.95370987,  5.03477556,  1.52804747],
       [-0.82597528,  1.52804747,  3.62683348]])

Función np.dot()
La función np.dot de la biblioteca numpy en Python se utiliza para realizar productos de matrices y vectores de manera eficiente.

Para entender cómo funciona np.dot, primero debemos comprender la multiplicación de matrices. La multiplicación de matrices es una operación que toma dos matrices y produce una nueva matriz. Esta operación se realiza combinando las filas de la primera matriz con las columnas de la segunda matriz.

1. Seleccionar una fila de la primera matriz.
2. Seleccionar una columna de la segunda matriz.
3. Multiplicar los elementos correspondientes de la fila y la columna seleccionadas y luego sumar los productos obtenidos.
4. Colocar el resultado en la posición correspondiente de la nueva matriz.
5. Repetir este proceso para todas las combinaciones de filas y columnas.

 link de imagen que explica la multiplicación de matrices: https://blogs.ugto.mx/rea/wp-content/uploads/sites/71/2021/11/Captura-de-Pantalla-2021-11-09-a-las-11.42.16.png

En este caso utiliza la función numpy.arange para crear un arreglo con 12 valores numéricos en incremento

In [24]:
arr_1=np.arange(12)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Nuevamente, vamos con el reshape que modifica la forma original del arreglo convirtiéndolo en la matriz de las dimensiones en el paréntesis que corresponde a 3 filas y 4 columnas

In [25]:
arr_1=np.arange(12).reshape(3,4)

In [26]:
arr_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

acá utilizando la función del reshape nuevamente cambia la forma de la matriz

In [15]:
arr_1.reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
arr_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
arr_1.transpose((0,1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Ahora con el transpose cambia la forma y posición de columnas convirtiéndolas en filas y viceversa usando las axis del arreglo en 2 dimensiones en el orden 0,1, entonces la primera fila se vuelve la primersa columna y así sucesivamente. Esto sirve cuando se desea obtener un patrón  específico y obtener un orden de transposición determinado y la siguiente en orden.

In [17]:
arr_1.transpose((1,0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

 1, 0, muestra que se efectuó un cambio, mientras que la primera permaneció igual al corresponder la primer axis con el 0 que es las filas. El orden siempre es filas(0)xcolumnas(1) al hacer este ejercicio de cambiar las axis.

El anterior es equivalente al arr_1.T, es decir, es igual a arr1_transpose((1,0)), que es la forma más comun de trasnponer una matriz o arreglo bidimensipnal

In [36]:
arr_1.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Ahora, se procede a realizar lo mismo, pero con arreglos de 3 dimensiones. Primero, con el arange se hizo el conteo incremental hasta 16 elementos comenzando desde el indice 0 guardando en un arreglo. Primeramente a la variable "arr" se le indica un rango del 0 al 15 usando numpy.

In [32]:
arr=np.arange(16)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Después, con el comando reshape se específica que será un arreglo de tres dimensiones con 2 filas cada uno por 4 columnas. El uso del "reshape" indica que el formato (2, 2, 4) es:

    El primer "2" es la cantidad de bloques que se van a generar.
    El segundo "2" es la cantidad de filas que se van a generar.
    El "4" es la cantidad de columnas que se van a generar.


In [34]:
arr=np.arange(16).reshape((2,2,4))

Primer valor indica la cantidad de bloques que habrá entre rango 1 a 15; segundo establece que tendrá 2 filas y será la misma cantidad por cada bloque, 4 es cuatro columnas. Descripción breve: .reshape((2, 2, 4)): Cambia la forma del array a 2 conjuntos, cada uno con 2 subconjuntos de 4 elementos.

In [35]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

 Primer bloque o "página" ([[ 0, 1, 2, 3], [ 4, 5, 6, 7]]): Contiene los números del 0 al 7 distribuidos en 2 filas de 4 columnas cada una.

Segundo bloque o "página" ([[ 8, 9, 10, 11], [12, 13, 14, 15]]): Contiene los números del 8 al 15, también distribuidos en 2 filas de 4 columnas cada una.


Luego, con el comando transpose que specifica el patrón deseado, se mueve la pruimea fila del primero a la primera fila del segundo y la primera fila del segundo a la primera fila del primero dejando alas columnas en su mismo sitio.


    En esta transposición, el primer eje (índice 0) y el segundo eje (índice 1) se intercambian, pero el tercer eje (índice 2) permanece igual.

        Antes: 2 páginas, cada una con 2 filas de 4 columnas.

        Después: 2 filas principales, cada una con 2 páginas de 4 columnas.

    Descripción breve: Cada "fila" ahora abarca lo que antes eran páginas, y las páginas ahora son las filas dentro de cada una de esas nuevas "filas principales".



In [29]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

 (1, 0, 2): Estos son los índices de los ejes en el orden que deseas que aparezcan después de la transposición. Originalmente, los ejes están en el orden (0, 1, 2). Al especificar (1, 0, 2), estás indicando que quieres que:
        El eje 1 original se convierta en el eje 0.
        (que era 2 igualmente(2,2,4), por lo que siguen siendo 2 bloques.)
        El eje 0 original se convierta en el eje 1.
        (que era 2 igualmente(2,2,4), su 0 del segundo blloque se va a la posición de mi eje uno del primer bloque).
        El eje 2 original permanezca en su lugar como el eje 2.

Entonces, si arr tiene la forma (dim0, dim1, dim2), después de aplicar arr.transpose(1,0,2), tendrá la forma (dim1, dim0, dim2).

In [30]:
arr.transpose((0,1,2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

sería el orden original, por lo que no hay cambios. Esta es una transposición trivial donde los ejes se dejan en su orden original. El resultado es simplemente el array original sin cambios.

In [31]:
arr.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

En este caso la cantidad de columnas que correspondía a 4 se convirtió en la cantidad de bloques que ahora son 4. Pasando de ser un arreglo tridimensional de forma (2,2,4) a (4,2,2), es decir cada bloque contiene 2 filas y 2 columnas ahora. En simple, comparando con el anterior se observa que cuando teníamos el orden de bloque por columna cambiado (1,0,2) manteniendo las columnas en su sitio, acá. El 0, 8, 4 y 12 pasaron a ser parte del mismo bloque, convirtiendo la columna en un bloque. Lo otro observable en relación al original es que la primea columna del primer bloque original es la misma que la primera columna del primer bloque resultante, mientras que la primera columna del segundo bloque original pasan a ser la segunda columna del resultado, luego, la segunda columna del primer bloque se transforma en la primera columna del segundo elemento y la segunda columna del segundo bloque se mueve a la segunda columna del segundo bloque y así sucesivamente.

array original
      ([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

Originalmente, los ejes están en el orden (0, 1, 2). Al especificar (2, 1, 0), estás indicando que quieres que:
        El eje 2 original permanece en el eje 2. Quedando las filas en su posición original, pasando a la segunda columna los del segundo bloque original, y cambiando de bloque según si la columna correspondiente era 0, 1, 2 o 3.
        El eje 1 original se convierta en el eje 3, teniendo los bloques 2 columnas.
        (que era igualmente(2,2,4), su 0 del segundo bloque se va a la posición de mi eje 3 del primer bloque).
        El eje 3 original se mueve al primero, modificando la cantidad de bloques.

Entonces, si arr tiene la forma (dim0, dim1, dim2), después de aplicar arr.transpose(1,0,2), tendrá la forma (dim2, dim1, dim0).

In [37]:
arr.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

 Aquí, el tercer eje se mueve al frente, el segundo eje permanece en su lugar, y el primer eje se mueve al final.

        Antes: 2 páginas, cada una con 2 filas de 4 columnas.

        Después: 4 columnas principales, cada una con 2 filas de 2 páginas.

Descripción breve: Cada "columna" ahora abarca lo que antes eran páginas, las páginas ahora son las filas dentro de cada una de esas nuevas "columnas principales".

In [38]:
arr.transpose((2,0,1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

En este caso, mi primera columna del primer bloque se convirtió en primera fila del primer bloque, y la primera columna del segundo bloque se volvio fila segunda del primer bloque.



Para mayor comprensión puedes visualizar las siguientes imágenes:

    https://files.codingninjas.in/article_images/numpy-transpose-in-python-2-1671427114.webp

    https://databasetown.com/wp-content/uploads/2020/02/Transpose-of-a-Matrix-in-Python.jpg

Y también la documentación de numpy:

    https://numpy.org/doc/stable/reference/generated/numpy.transpose.html


swap axes
Es una función que permite intercambiar dos ejes de un array. La utilidad está en que si se desea reorganizar las dimensiones de un array multidimensional para realizar operaciones o análisis específicos. 

Primero generamos un array y luego aplicamos la función swapaxes para
.swapaxes(0,1)

In [39]:
#Array
arr_ax = np.array([[1,1,1], [2,2,2], [3,3,3]])

In [40]:
arr_ax

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [41]:
#Hacemos un swapaxes para que intercambiemos filas, por columnas, queda de tal manera
arr_ax.swapaxes(0,1)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [42]:
#Otro ejemplo con array 3D
arr_swap = np.array([[[0, 1, 2],
                 [3, 4, 5]],

                [[6, 7, 8],
                 [9, 10, 11]]])


In [43]:
arr_swap

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [44]:
#Aplicamos Swapaxes para poder dejar el array con 2 filas cada una
arr_swap.swapaxes(0,2)

array([[[ 0,  6],
        [ 3,  9]],

       [[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]]])

Comparación swap axes versus transpose, transpose cambia el orden intercambiando filas y columnas y bloques, mientras que swap axes intercambia solo de 2 ejes como en el caso de transpose que convierte columnas en filas y viceversa siguiendo una regla de intercambio de ejes según como estuviera ordenado originalmente como vimos en el caso del 2,2,4, mientras que en el swap axes es más libre y flexible el intercambio de ejes en su reordenamiento y solo modifica 2 de los 3 ejes en el csso de arreglos multidimensionales. Versus el transpose que al indicarle los ejes, su orden indica cómo se permutan los ejes.

Pasra mayor información revisar: https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html