<a href="https://colab.research.google.com/github/davidlealo/sic_ai_2024/blob/main/004_machine_learning/%5Bgrupo-a%5DClase10_SIC_AI_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 10: Machine Learning




In [1]:
# Importar librerías iniciales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Datos del modelo
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]]) # Datos
y = np.dot(X, np.array([1, 2])) + 3 # Predicción

In [4]:
# Ejemplo de uso de SKLEARN
# Cragar la función/módulo/objeto
# sklearn.<family> import <Algoritmo de machine learning>
# En este caso <family> linear_model
from sklearn.linear_model import LinearRegression

# Instancia del algoritmo de machine learning
reg = LinearRegression()

# Ajuste (fit) del modelo
reg.fit(X, y)

# Predicción
reg.predict(np.array([[3, 5]]))

# Métricas
print(reg.score(X, y))
reg.coef_
reg.intercept_

1.0


3.0000000000000018

# Pasos para trabajar con sklearn

1. Importar el algoritmo en el formato

```Python
sklearn.<family> import <Algoritmo de machine learning>
````

2. Hacer una instancia del algoritmo

```Python
# Instancia del algoritmo de machine learning
reg = LinearRegression()
````

3. Ajuste del modelo
```Python
# Ajuste (fit) del modelo
reg.fit(X, y)
````

4. Predicción/transformación

```Python
# Predicción
reg.predict(np.array([[3, 5]]))
```


In [ ]:
# Para importar KNeighborsClassifier
# sklearn.<family> import <Algoritmo de machine learning>
from sklearn.neighbors import KNeighborsClassifier

# Instanciar, creo una variable para guardar el algoritmo y posteriormente
# trabajar con él como un objeto o con métodos, etc
# En el ejemplo n_neighbors=5 es un hiperparámetro
knn = KNeighborsClassifier(n_neighbors=3)

# es común que 'n_jobs= -1' para usar todos los procesadores de forma paralela


# Análisis de Datos: Variables Dependientes y Variables Independientes

En el análisis de datos, las variables se suelen clasificar en dos tipos principales: variables dependientes y variables independientes. Aquí tienes una descripción de cada una y su papel en el análisis de datos:

## Variables Independientes

Las variables independientes, también conocidas como variables explicativas o predictoras, son aquellas que se presumen causan o influyen en la variable dependiente. Son las variables que se manipulan o categorizan para observar su efecto en la variable dependiente.

**Ejemplos:**
- En un estudio sobre el rendimiento académico, las variables independientes podrían ser el número de horas de estudio, la asistencia a clases y el uso de recursos adicionales.
- En un análisis de marketing, las variables independientes podrían incluir el presupuesto publicitario, la duración de la campaña y el canal de distribución.

## Variables Dependientes

La variable dependiente es aquella que se presume está siendo afectada o influenciada por las variables independientes. Es la variable de interés que se está intentando predecir o explicar.

**Ejemplos:**
- En el estudio sobre rendimiento académico, la variable dependiente podría ser la calificación obtenida por los estudiantes.
- En el análisis de marketing, la variable dependiente podría ser el número de ventas o la tasa de conversión.

## Relación entre Variables Independientes y Dependientes

El objetivo del análisis de datos es entender cómo las variables independientes afectan a la variable dependiente. Esto se puede lograr mediante diferentes técnicas estadísticas y de modelado, como regresión lineal, análisis de varianza (ANOVA), análisis de regresión logística, entre otros.

**Ejemplo de Regresión Lineal:**
Supongamos que queremos analizar cómo el número de horas de estudio y la asistencia a clases (variables independientes) afectan la calificación de los estudiantes (variable dependiente). Podríamos usar una regresión lineal para modelar esta relación:

Calificación = β0 + β1 * (Horas de Estudio) + β2 * (Asistencia a Clases) + ε


Donde:
- `β0` es la intersección (constante)
- `β1` y `β2` son los coeficientes de las variables independientes
- `ε` es el término de error

## Ejemplo Práctico:

Supongamos que estamos investigando el impacto de la educación y la experiencia laboral en los salarios de los empleados.

- **Variables Independientes:** Nivel de educación (en años), Años de experiencia.
- **Variable Dependiente:** Salario (en dólares).

En este caso, podríamos realizar un análisis de regresión múltiple para determinar cómo cada una de estas variables independientes afecta el salario de los empleados.



In [5]:
import pandas as pd

In [6]:
import seaborn as sns

df = sns.load_dataset('titanic')

In [7]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [9]:
# dividir df en X e y

X = df.drop('survived', axis=1)
y = df['survived']

In [10]:
X

pclass     sex   age  sibsp  parch     fare embarked   class    who  \
0         3    male  22.0      1      0   7.2500        S   Third    man   
1         1  female  38.0      1      0  71.2833        C   First  woman   
2         3  female  26.0      0      0   7.9250        S   Third  woman   
3         1  female  35.0      1      0  53.1000        S   First  woman   
4         3    male  35.0      0      0   8.0500        S   Third    man   
..      ...     ...   ...    ...    ...      ...      ...     ...    ...   
886       2    male  27.0      0      0  13.0000        S  Second    man   
887       1  female  19.0      0      0  30.0000        S   First  woman   
888       3  female   NaN      1      2  23.4500        S   Third  woman   
889       1    male  26.0      0      0  30.0000        C   First    man   
890       3    male  32.0      0      0   7.7500        Q   Third    man   

     adult_male deck  embark_town alive  alone  
0          True  NaN  Southampton    no  False  
1         False    C    Cherbourg   yes  False  
2         False  NaN  Southampton   yes   True  
3         False    C  Southampton   yes  False  
4          True  NaN  Southampton    no   True  
..          ...  ...          ...   ...    ...  
886        True  NaN  Southampton    no   True  
887       False    B  Southampton   yes   True  
888       False  NaN  Southampton    no  False  
889        True    C    Cherbourg   yes   True  
890        True  NaN   Queenstown    no   True  

[891 rows x 14 columns]

In [11]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [12]:
# Importar el split de datos en train y test
from sklearn.model_selection import train_test_split

# configurar las variables
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [13]:
len(X_train) # Total 891

668

In [14]:
668/891

0.7497194163860831

In [15]:
len(X_test) # Total 891

223

In [16]:
223/891

0.250280583613917

In [17]:
len(y_train)

668

In [18]:
len(y_test)

223

In [19]:
X_train

pclass     sex   age  sibsp  parch      fare embarked   class    who  \
779       1  female  43.0      0      1  211.3375        S   First  woman   
320       3    male  22.0      0      0    7.2500        S   Third    man   
797       3  female  31.0      0      0    8.6833        S   Third  woman   
270       1    male   NaN      0      0   31.0000        S   First    man   
241       3  female   NaN      1      0   15.5000        Q   Third  woman   
..      ...     ...   ...    ...    ...       ...      ...     ...    ...   
453       1    male  49.0      1      0   89.1042        C   First    man   
317       2    male  54.0      0      0   14.0000        S  Second    man   
538       3    male   NaN      0      0   14.5000        S   Third    man   
125       3    male  12.0      1      0   11.2417        C   Third  child   
416       2  female  34.0      1      1   32.5000        S  Second  woman   

     adult_male deck  embark_town alive  alone  
779       False    B  Southampton   yes  False  
320        True  NaN  Southampton    no   True  
797       False  NaN  Southampton   yes   True  
270        True  NaN  Southampton    no   True  
241       False  NaN   Queenstown   yes  False  
..          ...  ...          ...   ...    ...  
453        True    C    Cherbourg   yes  False  
317        True  NaN  Southampton    no   True  
538        True  NaN  Southampton    no   True  
125       False  NaN    Cherbourg   yes  False  
416       False  NaN  Southampton   yes  False  

[668 rows x 14 columns]

In [20]:
y_train

779    1
320    0
797    1
270    0
241    1
      ..
453    1
317    0
538    0
125    1
416    1
Name: survived, Length: 668, dtype: int64

In [21]:
X_test.head()

pclass     sex   age  sibsp  parch      fare embarked  class    who  \
307       1  female  17.0      1      0  108.9000        C  First  woman   
244       3    male  30.0      0      0    7.2250        C  Third    man   
496       1  female  54.0      1      0   78.2667        C  First  woman   
106       3  female  21.0      0      0    7.6500        S  Third  woman   
876       3    male  20.0      0      0    9.8458        S  Third    man   

     adult_male deck  embark_town alive  alone  
307       False    C    Cherbourg   yes  False  
244        True  NaN    Cherbourg    no   True  
496       False    D    Cherbourg   yes  False  
106       False  NaN  Southampton   yes   True  
876        True  NaN  Southampton    no   True

In [22]:
y_test.head()

307    1
244    0
496    1
106    1
876    0
Name: survived, dtype: int64

In [26]:
df = sns.load_dataset('titanic')
X = df.drop('survived', axis=1)
y = df['survived']
# Importar el split de datos en train y test
from sklearn.model_selection import train_test_split

# configurar las variables
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [27]:
X_train.head()

pclass     sex    age  sibsp  parch      fare embarked   class    who  \
298       1    male    NaN      0      0   30.5000        S   First    man   
884       3    male  25.00      0      0    7.0500        S   Third    man   
247       2  female  24.00      0      2   14.5000        S  Second  woman   
478       3    male  22.00      0      0    7.5208        S   Third    man   
305       1    male   0.92      1      2  151.5500        S   First  child   

     adult_male deck  embark_town alive  alone  
298        True    C  Southampton   yes   True  
884        True  NaN  Southampton    no   True  
247       False  NaN  Southampton   yes  False  
478        True  NaN  Southampton    no   True  
305       False    C  Southampton   yes  False

# Ejemplo de Regresión Lineal con scikit-learn

Este ejemplo demuestra cómo dividir los datos, ajustar un modelo de regresión lineal, realizar predicciones y calcular la matriz de confusión utilizando la biblioteca scikit-learn en Python.

## Importar las bibliotecas necesarias

```python
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix, mean_squared_error


In [23]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix, mean_squared_error

## Cargar los datos
Suponiendo que tenemos un DataFrame df con las variables independientes X y la variable dependiente y:

In [24]:
# Ejemplo de datos
df = pd.DataFrame({
    'Horas de Estudio': [1, 2, 3, 4, 5],
    'Asistencia a Clases': [2, 3, 4, 5, 6],
    'Calificación': [3, 4, 5, 6, 7]
})

X = df[['Horas de Estudio', 'Asistencia a Clases']]
y = df['Calificación']


In [ ]:
print(X)

   Horas de Estudio  Asistencia a Clases
0                 1                    2
1                 2                    3
2                 3                    4
3                 4                    5
4                 5                    6


In [ ]:
print(y)

0    3
1    4
2    5
3    6
4    7
Name: Calificación, dtype: int64


## Dividir los datos en conjuntos de entrenamiento y prueba


In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
# sklearn.model_selection.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
# Primero son los datos que están en las variables X e y
# Segundo: test_size el % que queda para el test. Por ejemplo si test_size es 0.2 quiere decir que tenemos
# un 80% para entrenamiento y un 20% para testear
 # random_state es una semilla para poder comprar resultados sin perder lo aleatorio
 # shuffle
 # stratify

In [ ]:
print(X_train)

   Horas de Estudio  Asistencia a Clases
4                 5                    6
2                 3                    4
0                 1                    2
3                 4                    5


In [ ]:
print(X_test)

   Horas de Estudio  Asistencia a Clases
1                 2                    3


In [ ]:
print(y_train)

4    7
2    5
0    3
3    6
Name: Calificación, dtype: int64


In [ ]:
print(y_test)

1    4
Name: Calificación, dtype: int64


## Ajustar el modelo de regresión lineal


In [ ]:
# Instanciar
model = LinearRegression()

In [ ]:
# Ajuste del modelo
model.fit(X_train, y_train)

LinearRegression()

## Realizar predicciones


In [ ]:
# Predicción
y_pred = model.predict(X_test)

## Calcular la matriz de confusión
Para calcular la matriz de confusión, primero necesitamos convertir las predicciones continuas a categorías. Supongamos que usamos un umbral para clasificar las predicciones:



In [ ]:
# Convertir las predicciones y los valores reales a categorías usando un umbral (por ejemplo, 5)
threshold = 5
y_pred_class = np.where(y_pred >= threshold, 1, 0)
y_test_class = np.where(y_test >= threshold, 1, 0)

# Calcular la matriz de confusión
conf_matrix = confusion_matrix(y_test_class, y_pred_class)
print(conf_matrix)


[[1]]


## Calcular el error cuadrático medio (MSE)
Aunque no es una matriz de confusión, es común evaluar el rendimiento de una regresión lineal con el MSE:



In [ ]:
mse = mean_squared_error(y_test, y_pred)
print(f'Error Cuadrático Medio (MSE): {mse}')

Error Cuadrático Medio (MSE): 0.0


# Accuracy

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
# Accuracy
accuracy = accuracy_score(y_test_class, y_pred_class)
print(f'Accuracy: {accuracy}')

Accuracy: 1.0


# Ejemplos de la presentación

In [28]:
# En la presentación nos piden cargar el dataset de https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html#sklearn.datasets.load_breast_cancer
from sklearn.datasets import load_breast_cancer
# Datos importados de la base de juguete

In [29]:
# ver el tipo
type(load_breast_cancer())

sklearn.utils._bunch.Bunch

In [30]:
# Guardar la base de juguete en la variable data
data = load_breast_cancer()

In [31]:
print(data)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [35]:
# Convertir en df la variable data
pd.DataFrame(data['data'], columns=data['feature_names'])
# Esto va a ser nuestra variable independiente::: X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [40]:
# Esto va a ser nuestra variable dependiente::: y con el nombre de la columna
pd.DataFrame(data['target'], columns=['target'])

target
0         0
1         0
2         0
3         0
4         0
..      ...
564       0
565       0
566       0
567       0
568       1

[569 rows x 1 columns]

In [34]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [41]:
# importar slplit de scikitlearn
from sklearn.model_selection import train_test_split

In [42]:
# Entender la función con help
help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
    Split arrays or matrices into random train and test subsets.
    
    Quick utility that wraps input validation,
    ``next(ShuffleSplit().split(X, y))``, and application to input data
    into a single call for splitting (and optionally subsampling) data into a
    one-liner.
    
    Read more in the :ref:`User Guide <cross_validation>`.
    
    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.
    
    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to

In [43]:
# contar rows
len(data['data'])

569

In [44]:
len(data.data)

569

In [45]:
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target)
# Split de datos con hiperparámetros con valores por defecto

In [46]:
len(X_train)

426

In [47]:
426/569

0.7486818980667839

In [ ]:
print(X_train)

[[1.222e+01 2.004e+01 7.947e+01 ... 8.088e-02 2.709e-01 8.839e-02]
 [1.328e+01 2.028e+01 8.732e+01 ... 1.492e-01 3.739e-01 1.027e-01]
 [2.092e+01 2.509e+01 1.430e+02 ... 2.542e-01 2.929e-01 9.873e-02]
 ...
 [9.876e+00 1.727e+01 6.292e+01 ... 5.588e-02 2.989e-01 7.380e-02]
 [1.426e+01 1.817e+01 9.122e+01 ... 7.530e-02 2.636e-01 7.676e-02]
 [1.340e+01 2.052e+01 8.864e+01 ... 2.051e-01 3.585e-01 1.109e-01]]


# Mirando otros datasets

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()

In [ ]:
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [ ]:
from sklearn.datasets import load_diabetes

In [ ]:
diabetes = load_diabetes()

In [ ]:
print(diabetes)

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]]), 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
  

# La presentación sigue

In [ ]:
# Ejemplo de nla slide 27
# Cragar desde scikit-learn
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

# Guardar en la variable data el dataset cargado
data = load_breast_cancer()

# Dividir el data en sets de entrenamiento y testeo
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, random_state = 42)

# Instanciar el modelo con el hiperparámetro de criterio de entropía en la variable modelo
model = DecisionTreeClassifier(criterion = 'entropy')

# Ajustar el modelo con el set de entrenamiento
model.fit(X_train, y_train)

# Realizar predicciones con el set de testeo
y_pred = model.predict(X_test)

y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
# Guardar la predicción en la variable pred
pred = model.predict(X_test)

# imprimer len(pred)
print('len(pred)')
print(len(pred))

# Reshape de pred en 2d
pred_2d = pred.reshape(len(pred),1)
pred_2d

len(pred)
143


array([[1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [ ]:
# reshape del test y
y_test_2d = y_test.reshape(len(y_test),1)
y_test_2d

array([[1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
    

In [ ]:
# Definir dos df uno con las predicciones de y otro con los resultados reales
df1 = pd.DataFrame(pred_2d, columns=['pred'])
df2 = pd.DataFrame(y_test_2d, columns=['real'])

In [ ]:
# Concatenar ambos df
pd.concat([df1, df2], axis=1)

pred  real
0       1     1
1       0     0
2       0     0
3       1     1
4       1     1
..    ...   ...
138     1     1
139     0     0
140     1     1
141     0     0
142     1     1

[143 rows x 2 columns]

In [ ]:
# df concatenado en una variable pd_concat
pd_concat = pd.concat([df1, df2], axis=1)

# Columnas de pd_concat
pd_concat.columns

Index(['pred', 'real'], dtype='object')

In [ ]:
# Comparar ambas columnas
pd_concat['pred'] == pd_concat['real']

0      True
1      True
2      True
3      True
4      True
       ... 
138    True
139    True
140    True
141    True
142    True
Length: 143, dtype: bool

In [ ]:
# Quedamos en la slide 27
# Estudiar https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html