<a href="https://colab.research.google.com/github/davidlealo/sic_ai_2024/blob/main/004_machine_learning/%5Btrabajo-en-clases%5DClase11-GRUPO-B_SIC_AI_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 11: Machine Learning




# La presentación sigue en la página 27

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Cargar desde scikit-learn
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [3]:
# Guardar en la variable data el dataset cargado
data = load_breast_cancer()

In [4]:
# Dividir el data en sets de entrenamiento y testeo
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, random_state = 42)

In [5]:
# Instanciar el modelo con el hiperparámetro de criterio de entropía en la variable modelo
model = DecisionTreeClassifier(criterion = 'entropy')

In [6]:
# Ajustar el modelo con el set de entrenamiento
model.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [7]:
# Realizar predicciones con el set de testeo
y_pred = model.predict(X_test)

In [8]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [9]:
# Guardar la predicción en la variable pred
pred = model.predict(X_test)

In [10]:
# imprimer len(pred)
print('len(pred)')
print(len(pred))

len(pred)
143


In [11]:
print(pred)

[1 0 0 1 1 0 0 0 0 1 1 0 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 1 0 1 0 1 1 1 0 1 1 1 0 1 0 0 1 1 0 0 0 1 1 1 0 0 1 1 0 1 0 1]


In [12]:
# Reshape de pred en 2d
pred_2d = pred.reshape(len(pred),1)
pred_2d

array([[1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [13]:
y_test

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1])

In [14]:
# reshape del test y
y_test_2d = y_test.reshape(len(y_test),1)
y_test_2d

array([[1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
    

In [15]:
# Definir dos df uno con las predicciones de y otro con los resultados reales
df1 = pd.DataFrame(pred_2d, columns=['pred'])
df2 = pd.DataFrame(y_test_2d, columns=['real'])

In [48]:
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [16]:
# Concatenar ambos df
pd.concat([df1, df2], axis=1)

pred  real
0       1     1
1       0     0
2       0     0
3       1     1
4       1     1
..    ...   ...
138     1     1
139     0     0
140     1     1
141     0     0
142     1     1

[143 rows x 2 columns]

In [17]:
# df concatenado en una variable pd_concat
pd_concat = pd.concat([df1, df2], axis=1)

# Columnas de pd_concat
pd_concat.columns

Index(['pred', 'real'], dtype='object')

In [47]:
# Comparar ambas columnas
pd_concat['pred'] == pd_concat['real']

0      True
1      True
2      True
3      True
4      True
       ... 
138    True
139    True
140    True
141    True
142    True
Length: 143, dtype: bool

In [19]:
prediccion_final = pd_concat['pred'] == pd_concat['real']

In [20]:
print(len(prediccion_final))

143


In [21]:
prediccion_final.sum()

136

In [22]:
137/143

0.958041958041958

# Predicción d e lluvia mañana

0 = no llueve
1 = llueve


TP = ped.llueve & real.llueve

FP = ped.llueve & real.no llueve

FN = ped.no llueve & real.llueve

TN = ped.no llueve & real.No llueve

## Accuracy

TP + TN / (TP + FP + FN + TN)

### Caso donde el accuracy no es bueno

Muestra donde:

100 casos

TP = 0

FP = 90

FN = 0

TN = 10

In [23]:
accuracy = (0 + 10)/100

accuracy

0.1

Muestra donde:

100 casos

TP = 0

FP = 10

FN = 0

TN = 90

In [24]:
accuracy = (0 + 90)/100

accuracy

0.9

In [25]:
# importamos la library
from sklearn.preprocessing import StandardScaler

# instanciar
scaler = StandardScaler()

In [26]:
X_train

array([[1.289e+01, 1.312e+01, 8.189e+01, ..., 5.366e-02, 2.309e-01,
        6.915e-02],
       [1.340e+01, 2.052e+01, 8.864e+01, ..., 2.051e-01, 3.585e-01,
        1.109e-01],
       [1.296e+01, 1.829e+01, 8.418e+01, ..., 6.608e-02, 3.207e-01,
        7.247e-02],
       ...,
       [1.429e+01, 1.682e+01, 9.030e+01, ..., 3.333e-02, 2.458e-01,
        6.120e-02],
       [1.398e+01, 1.962e+01, 9.112e+01, ..., 1.827e-01, 3.179e-01,
        1.055e-01],
       [1.218e+01, 2.052e+01, 7.722e+01, ..., 7.431e-02, 2.694e-01,
        6.878e-02]])

In [27]:
# Datos previos a la estandarización
df_scale_previous = pd.DataFrame(data.data)

In [28]:
scaler.fit(X_train)

StandardScaler()

In [29]:
X_train = scaler.transform(X_train)

In [30]:
# Datos posterior a la estandarización
df_scale_after = pd.DataFrame(X_train)

In [31]:
# Imprimir df_scaler_previous
df_scale_previous

0      1       2       3        4        5        6        7       8   \
0    17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010  0.14710  0.2419   
1    20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690  0.07017  0.1812   
2    19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740  0.12790  0.2069   
3    11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140  0.10520  0.2597   
4    20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800  0.10430  0.1809   
..     ...    ...     ...     ...      ...      ...      ...      ...     ...   
564  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390  0.13890  0.1726   
565  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400  0.09791  0.1752   
566  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251  0.05302  0.1590   
567  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140  0.15200  0.2397   
568   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000  0.00000  0.1587   

          9   ...      20     21      22      23       24       25      26  \
0    0.07871  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.05667  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.05999  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.09744  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.05883  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.05623  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.05533  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05648  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.07016  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.05884  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         27      28       29  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 30 columns]

In [32]:
df_scale_after

0         1         2         3         4         5         6   \
0   -0.349138 -1.438513 -0.411726 -0.390479 -1.863662 -1.268607 -0.826171   
1   -0.204687  0.312640 -0.133673 -0.275880  1.078073  0.863546  0.726314   
2   -0.329312 -0.215072 -0.317394 -0.364357 -1.579880 -0.457451 -0.597310   
3    1.027403  2.089824  1.046922  0.917584  0.316303  0.562037  1.048527   
4    1.828969  0.696001  1.763681  1.783821 -0.333674  0.628175  0.974660   
..        ...       ...       ...       ...       ...       ...       ...   
421 -1.482661 -1.078817 -1.363286 -1.154195  0.162946  0.984150 -0.017962   
422 -0.703187 -0.205607 -0.688544 -0.680910  1.336057 -0.015692 -0.213582   
423  0.047396 -0.562937 -0.065292 -0.062691 -2.240606 -1.473633 -1.021664   
424 -0.040408  0.099662 -0.031514 -0.155663  0.748426  0.209953  0.320044   
425 -0.550238  0.312640 -0.604098 -0.551143 -1.105476 -1.208500 -0.810506   

           7         8         9   ...        20        21        22  \
0   -0.952866 -1.729368 -0.941541  ... -0.542685 -1.655655 -0.589864   
1    0.898441  1.178770  1.474377  ...  0.041487  0.689899  0.194128   
2   -0.764588  0.275343 -0.501024  ... -0.435901 -0.148985 -0.320159   
3    0.930437 -0.325697 -0.477474  ...  1.113515  2.165006  1.165793   
4    1.265740 -0.131572 -1.713139  ...  1.471556  0.387568  1.556276   
..        ...       ...       ...  ...       ...       ...       ...   
421 -0.503063  0.379872  3.767006  ... -1.356547 -1.634059 -1.341770   
422 -0.340964  0.002822  0.359231  ... -0.643188  0.623452 -0.647074   
423 -1.097247 -1.090996 -1.225522  ... -0.272584 -0.806803 -0.376764   
424  0.446522 -0.489956  0.392478  ...  0.173397  0.879270  0.212290   
425 -0.794470 -0.228635 -0.808555  ... -0.601311  1.218146 -0.675225   

           23        24        25        26        27        28        29  
0   -0.525560 -1.510669 -0.891500 -0.750217 -0.916711 -0.925086 -0.808411  
1   -0.051934  1.129415  0.923942  1.222217  1.436560  1.149559  1.569111  
2   -0.446032 -1.634396 -0.106752 -0.539891 -0.723713  0.534970 -0.619348  
3    0.997696  0.383604  0.860948  1.872819  1.310691  0.152884  0.421636  
4    1.385595 -0.577759  0.296680  0.595768  1.232995  0.050452 -1.406351  
..        ...       ...       ...       ...       ...       ...       ...  
421 -1.043821 -0.452739 -0.027674 -0.625430 -1.006838 -1.014510  1.426745  
422 -0.623509  1.620874  0.122440  0.098634  0.142137 -0.117015  0.434165  
423 -0.334976 -1.962898 -1.322676 -1.152453 -1.232624 -0.682827 -1.261137  
424 -0.007830  1.297546  0.730938  0.700428  1.088480  0.489445  1.261600  
425 -0.577280 -0.814867 -1.066276 -0.770847 -0.595824 -0.299115 -0.829481  

[426 rows x 30 columns]

# Ejemplos de validación

##K-Fold Cross Validation
###Descripción:
K-Fold Cross Validation divide el conjunto de datos en
𝑘
k pliegues (o "folds"). El modelo se entrena
𝑘
k veces, cada vez utilizando
𝑘
−
1
k−1 pliegues para el entrenamiento y el pliegue restante para la validación. El proceso se repite
𝑘
k veces, con cada pliegue utilizado exactamente una vez para la validación.

Ventajas:

Mayor uso de los datos: Cada muestra se utiliza tanto para entrenamiento como para validación, lo que maximiza el uso de los datos disponibles.
Estimaciones más estables: Al promediar los resultados de
𝑘
k entrenamientos diferentes, se obtiene una estimación más estable y robusta del rendimiento del modelo.
Flexibilidad: Se puede ajustar el número de pliegues (
𝑘
k) para equilibrar el sesgo y la varianza.
Desventajas:

Costo computacional: Requiere entrenar el modelo
𝑘
k veces, lo que puede ser computacionalmente costoso, especialmente para modelos complejos o grandes conjuntos de datos.
Menor estimación de error: Puede subestimar el error de generalización cuando se usa con
𝑘
k pequeño.
##Leave-One-Out Cross Validation (LOO)
###Descripción:
Leave-One-Out Cross Validation es un caso especial de K-Fold donde el número de pliegues (
𝑘
k) es igual al número de muestras en el conjunto de datos. En cada iteración, se usa una sola muestra para la validación y el resto para el entrenamiento. Este proceso se repite tantas veces como muestras haya en el conjunto de datos.

Ventajas:

Máximo uso de datos para el entrenamiento: En cada iteración, casi todas las muestras se utilizan para el entrenamiento, lo que puede ser beneficioso para conjuntos de datos pequeños.
Estimación sin sesgo: Proporciona una estimación sin sesgo del error de generalización, ya que cada muestra se valida exactamente una vez.
Desventajas:

Costo computacional extremadamente alto: Requiere entrenar el modelo tantas veces como muestras haya en el conjunto de datos, lo que puede ser prohibitivo para grandes conjuntos de datos.
Alta varianza: Las estimaciones de error pueden tener alta varianza, ya que cada modelo se entrena con un conjunto de datos ligeramente diferente.
Ejemplo Comparativo
Para ilustrar las diferencias entre K-Fold y LOO, podemos realizar una comparación práctica usando un conjunto de datos. Aquí, utilizaremos el conjunto de datos Iris con un modelo de Random Forest:

In [33]:
# from sklearn.<familia> import <Algoritmo>

In [34]:
# Importar las library
from sklearn.model_selection import KFold, LeaveOneOut, cross_val_score
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [36]:
# Cargar el conjunto de datos Iris
iris = load_iris()
X, y = iris.data, iris.target

In [37]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [38]:
# Crear el modelo instanciando y definiendo los hiperparámetros
model = RandomForestClassifier(random_state=42)

In [39]:
# K-Fold Cross Validation instanciamos la técnica
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Realizar la validación cruzada
kf_scores = cross_val_score(model, X, y, cv=kf)

In [40]:
print("Scores de K-Fold Cross Validation: ", kf_scores)
print("Media de los scores: ", np.mean(kf_scores))

Scores de K-Fold Cross Validation:  [1.         0.96666667 0.93333333 0.93333333 0.96666667]
Media de los scores:  0.9600000000000002


In [41]:
# Leave-One-Out Cross Validation instanciar
loo = LeaveOneOut()

In [42]:
# usamos la técnica
loo_scores = cross_val_score(model, X, y, cv=loo)

In [43]:
print(len(loo_scores))

150


In [44]:
print("Scores de Leave-One-Out Cross Validation: ", loo_scores)
print("Media de los scores: ", np.mean(loo_scores))

Scores de Leave-One-Out Cross Validation:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]
Media de los scores:  0.9533333333333334


In [ ]:
# Revisar https://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators

# Versión ES https://qu4nt.github.io/sklearn-doc-es/modules/cross_validation.html

In [49]:
from sklearn.model_selection import RepeatedKFold

In [50]:
rkf = RepeatedKFold(n_splits=5, n_repeats=3, random_state=42)

In [51]:
rkf_scores = cross_val_score(model, X, y, cv=rkf)

In [52]:
rkf_scores

array([1.        , 0.96666667, 0.93333333, 0.93333333, 0.96666667,
       0.96666667, 1.        , 0.9       , 1.        , 0.93333333,
       0.96666667, 0.86666667, 1.        , 1.        , 0.9       ])

In [53]:
np.mean(rkf_scores)

0.9555555555555556