## Coding Exercise #0207

### 1. Correlation:

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st
import os

In [2]:
# Go to the directory where the data file is located. 
#  os.chdir(r'~~')                # Please, replace the path with your own.  

In [3]:
# Read in the data.
df = pd.read_csv('data_iris.csv', header='infer')

In [4]:
df.shape

(150, 5)

In [5]:
df.head(3)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [6]:
# Set aside two variables.
x = df['Petal.Length']
y = df['Sepal.Length']

#### 1.1. Pearson:

In [7]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.pearsonr(x,y),3)           

array([0.872, 0.   ])

In [8]:
# Using the Pandas function.
x.corr(y)

0.871754157304871

In [9]:
# Correlation array.
np.round(df[['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width']].corr(),3)               

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Sepal.Length         1.000       -0.109         0.872        0.818
Sepal.Width         -0.109        1.000        -0.421       -0.357
Petal.Length         0.872       -0.421         1.000        0.963
Petal.Width          0.818       -0.357         0.963        1.000

#### 1.2. Spearman:

In [10]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.spearmanr(x,y),3)          

array([0.881, 0.   ])

#### 1.3. Kendall:

In [11]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.kendalltau(x,y),3)         # Correlation coefficient and p-value.

array([0.718, 0.   ])

### 2. Interval Estimation of the Correlation:

In [12]:
# Read in another data set.
df = pd.read_csv('data_studentlist.csv', header='infer')

In [13]:
df.head(3)

name gender  age  grade absence bloodtype  height  weight
0   Jared Diamond      M   23      3       Y         O   165.3    68.2
1  Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2    Brian Martin      M   24      4       N         B   175.0    80.1

In [14]:
# Set aside two variables.
x = df.height
y = df.weight

#### 2.2. Confidence Interval of the Pearson Correlation: 

In [15]:
# Apply the Fisher's z-transformation.
# See the lecture.
n = len(x)
r = x.corr(y)
z = np.arctanh(r)
std_error_z = 1/np.sqrt(n-3)

In [16]:
# 95% confidence interval. 
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.975)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.975)*std_error_z)}

{'low': 0.26960396330592223, 'high': 0.8677953581441814}

In [17]:
# 99% confidence interval.
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.995)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.995)*std_error_z)}

{'low': 0.11137578298592947, 'high': 0.9030812794020874}