## 1.2 NumPy Array Basics

### How to import NumPy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.3'

### NumPy Array Basics

In [3]:
np.array([1,3,4,5,9])

array([1, 3, 4, 5, 9])

In [4]:
arr1=np.array([1,3,5,7,9])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([1,3,5,7,9])

In [7]:
id(arr1)

4476782800

In [8]:
id(arr2)

4476783952

In [9]:
arr3=arr1

In [10]:
print(id(arr1))
print(id(arr3))

4476782800
4476782800


In [11]:
arr4=np.copy(arr1)

In [12]:
arr4

array([1, 3, 5, 7, 9])

In [13]:
id(arr4)

4476782416

In [14]:
type((1,3,5,7,9))

tuple

In [15]:
np.array((1,3,5,7,9))

array([1, 3, 5, 7, 9])

In [16]:
type({'one':1, 'two':2, 'three':2})

dict

In [17]:
np.array({'one':1, 'two':2, 'three':2})

array({'one': 1, 'two': 2, 'three': 2}, dtype=object)

In [18]:
{1,2,2,2,2,3,3,3,4}

{1, 2, 3, 4}

In [19]:
type({1,2,2,2,2,3,3,3,4})

set

In [20]:
np.array({1,2,2,2,2,3,3,3,4})

array({1, 2, 3, 4}, dtype=object)

In [21]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
[i for i in np.arange(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [26]:
len10=np.arange(10)

In [27]:
len(len10)

10

In [28]:
len10.size

10

In [29]:
np.array([111,2.3,True])

array([111. ,   2.3,   1. ])

In [30]:
arr5=np.array([111,2.3,True])

In [31]:
type(arr5[0])

numpy.float64

In [32]:
arr6=np.array([111,2.3,'hi'])

In [33]:
arr6[0]

'111'

In [34]:
type(arr6[0])

numpy.str_

In [35]:
2**8

256

In [36]:
np.array(['apple', 'banana', 'strawberry'])

array(['apple', 'banana', 'strawberry'], dtype='<U10')

In [37]:
arr7=np.array(['apple', 'banana', 'strawberry'])

In [38]:
type(arr7[0])

numpy.str_

In [39]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [40]:
np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [41]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### Multidimensional Arrays

In [43]:
li1=[[1,2,3],[4,5,6],[7,8,9]]

In [44]:
li1[0][0]

1

In [45]:
np.array(li1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr2d=np.array(li1)

In [47]:
arr2d.ndim

2

In [48]:
arr1d=np.array([1,3,5,7,9])

In [49]:
arr1d.ndim

1

In [50]:
np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [51]:
arr3d=np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

In [52]:
arr3d.ndim

3

In [53]:
arr3d[0][0][0]

1

In [54]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
arr2dZero=np.zeros((2,3))

In [56]:
type(arr2dZero[0][0])

numpy.float64

In [57]:
arr2dZero2=np.zeros((2,3), dtype='int64')

In [58]:
arr2dZero2

array([[0, 0, 0],
       [0, 0, 0]])

In [59]:
type(arr2dZero2[0][0])

numpy.int64

In [60]:
arr2dZero2.astype('float32')

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [61]:
arr2dZero2=arr2dZero2.astype('float32')

In [62]:
arr2dZero2

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

### Properties of the NumPy Array

In [63]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [64]:
a.size

9

In [65]:
a.shape

(3, 3)

In [66]:
a.ndim

2

In [67]:
a1=np.array([2,5,1,3])

In [68]:
a1.shape

(4,)

### Reshape

In [69]:
a2=np.arange(15)

In [70]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [71]:
a2.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [72]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
a2=a2.reshape((3,5))

In [74]:
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [75]:
a3=np.arange(15)

In [76]:
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [77]:
a3.shape=(5,3)

In [78]:
a3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Random Numbers

In [79]:
data=np.random.randn(2,3)

In [80]:
data

array([[0.55129032, 1.80922556, 0.24581826],
       [0.1018971 , 0.42817383, 0.46971557]])

In [81]:
np.mean(data)

0.601020107292672

In [82]:
data2=np.random.randn(100,100)

In [83]:
np.mean(data2)

-0.011369300075537634

In [84]:
data2

array([[-0.82620057,  1.87304659,  0.3703832 , ..., -0.32061796,
        -1.19221677,  0.21320981],
       [ 0.88426285,  0.20191958,  2.13250876, ..., -0.05212199,
        -0.18155744,  1.23161669],
       [ 0.55100359,  1.94964974,  0.34422172, ...,  0.87478908,
        -0.55155194,  0.18521703],
       ...,
       [-0.22684233,  0.8768658 ,  0.30988136, ..., -3.27758554,
        -0.52661172,  0.22899604],
       [ 0.407585  , -0.19807574, -0.9728895 , ...,  2.1726469 ,
         0.06946691, -0.92372109],
       [-0.12845044, -1.46199168,  0.1678034 , ..., -1.47977018,
        -0.37330327, -0.90666062]])

In [85]:
data3=np.random.randn(100,100)
np.mean(data3)

-0.0015806190513654394

In [86]:
data3

array([[ 1.27805671, -0.55812624, -0.04575613, ..., -1.59865812,
         0.58393257,  0.29011717],
       [-0.8707763 ,  1.12783752,  1.04209089, ..., -0.25088789,
        -0.26079617,  0.40218566],
       [-2.01637648,  0.01299273, -1.2430723 , ..., -0.08478432,
         0.34884704,  0.01064548],
       ...,
       [-1.26977253, -1.16822388,  1.55837003, ...,  1.13994434,
         0.64961919,  1.06677066],
       [-0.45258692,  0.34309153, -1.47162394, ...,  0.42194509,
         0.62131134, -0.62867773],
       [-0.61692044,  0.09967813, -0.61037562, ...,  0.14373665,
        -0.49319039,  0.28312379]])

In [87]:
np.arange(1000000)

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [88]:
list(range(1000000))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [89]:
type(np.arange(1000000))

numpy.ndarray

In [90]:
%time for i in range(1000): np.arange(1000000)*2

CPU times: user 530 ms, sys: 427 ms, total: 957 ms
Wall time: 956 ms


In [91]:
%time for i in range(1000): list(range(1000000))*2

CPU times: user 12.8 s, sys: 2.7 s, total: 15.5 s
Wall time: 15.5 s


### Adding Elements to NumPy Arrays

In [92]:
a=np.array([1,2,3])

In [93]:
b=np.append(a, [4,5,6])

In [94]:
b

array([1, 2, 3, 4, 5, 6])

In [95]:
a=np.array([[1,2],[3,4]])

In [96]:
a

array([[1, 2],
       [3, 4]])

In [97]:
b=np.append(a,[[9,9]], axis=0)

In [98]:
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [99]:
c=np.append(a,[[9],[9]], axis=1)

In [100]:
c

array([[1, 2, 9],
       [3, 4, 9]])

### Deleting Elements from NumPy Arrays

In [101]:
a=np.array([[1,2,3],[4,5,6]])

In [102]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
np.delete(a, 0)

array([2, 3, 4, 5, 6])

In [104]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
np.delete(a, 0, axis=0)

array([[4, 5, 6]])

In [106]:
np.delete(a, 1, axis=1)

array([[1, 3],
       [4, 6]])

## 1.3. NumPy Array Operations

### Basic Operations

In [107]:
a=[1,2,3]

In [108]:
b=[4,5,6]

In [109]:
a+b

[1, 2, 3, 4, 5, 6]

In [110]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [111]:
arr1+arr2

array([5, 7, 9])

In [112]:
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)

1
3
(3,)


In [113]:
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)

1
3
(3,)


In [114]:
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [115]:
a=[1,2,3]
3*a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [116]:
b=np.array([1,2,3])
3*b

array([3, 6, 9])

In [117]:
b

array([1, 2, 3])

In [118]:
np.repeat(b,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [119]:
np.tile(b,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [120]:
c=np.arange(9)

In [121]:
c=c.reshape(3,3)

In [122]:
c.shape

(3, 3)

In [123]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [124]:
np.tile(c,3)

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8]])

In [125]:
arr2

array([4, 5, 6])

In [126]:
arr2**2

array([16, 25, 36])

In [127]:
arr1 / (arr2**2)

array([0.0625    , 0.08      , 0.08333333])

In [128]:
arr3=np.array([10,20,30,40])

In [129]:
arr3

array([10, 20, 30, 40])

In [130]:
arr3 > 10

array([False,  True,  True,  True])

In [131]:
x=np.array([0,1,2,3])

In [132]:
x**3

array([ 0,  1,  8, 27])

In [133]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [134]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
x=np.arange(1,11)

In [136]:
x.sum()

55

In [137]:
x.mean()

5.5

In [138]:
x_mean=x.mean()

In [139]:
x-x_mean

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [140]:
(x-x_mean)**2

array([20.25, 12.25,  6.25,  2.25,  0.25,  0.25,  2.25,  6.25, 12.25,
       20.25])

In [141]:
dev=(x-x_mean)**2

In [142]:
dev.sum()

82.5

In [143]:
dev.sum() / x.size

8.25

In [144]:
x.var()

8.25

In [145]:
np.sqrt(x.var())

2.8722813232690143

In [146]:
x.std()

2.8722813232690143

In [147]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [148]:
x=np.arange(1,7)

In [149]:
x

array([1, 2, 3, 4, 5, 6])

In [150]:
x.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [151]:
x.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [152]:
x.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [153]:
x=x.reshape(2,3)

In [154]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
x.mean(axis=0)

array([2.5, 3.5, 4.5])

In [156]:
x.mean(axis=1)

array([2., 5.])

In [157]:
np.random.seed(123)

In [158]:
np.random.randint(10)

2

In [159]:
np.random.randint(1,11)

3

In [160]:
while True:
    num=np.random.randint(1,11)
    print(num)
    if (num==10):
        break

7
2
4
10


In [161]:
while True:
    num=np.random.randint(1,11)
    print(num)
    if (num==11):
        break

In [162]:
x=np.array([0, 1, 2, 3, 4, 5])

In [163]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [164]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [165]:
np.random.seed(123)
a = np.random.randint(1, 11, size=1000)

In [166]:
a

array([ 3,  3,  7,  2,  4, 10,  7,  2,  1,  2, 10,  1,  1, 10,  4,  5,  1,
        1,  5,  2,  8,  4,  3,  5,  8,  3,  5,  9,  1,  8, 10,  4,  5,  7,
        2,  6,  7,  3,  2,  9,  4,  6,  1,  3,  7,  3,  5,  5,  7,  4,  1,
        7,  5,  8,  7,  8,  2,  6,  8, 10,  3,  5,  9,  2,  3,  2,  2,  4,
        6, 10,  1,  9,  2,  7,  4,  4,  6, 10,  8, 10,  3,  4,  4,  4,  9,
        7, 10,  8,  7,  4, 10,  7,  7,  7,  2,  4,  5,  4,  2,  1,  6,  9,
        7,  9, 10,  2,  1,  4,  2,  4,  5,  8,  7,  2,  5,  4,  4,  8,  7,
        9,  7,  5,  5,  8,  1,  1, 10,  9,  9,  5,  9,  7,  2,  7,  9,  8,
       10,  2,  8,  2,  8, 10,  9,  8,  2,  4,  2,  9,  8,  6,  2,  3,  6,
        3,  3, 10,  4,  3,  7,  8, 10,  2,  4,  9,  4,  8, 10, 10,  4,  4,
        6,  7,  1,  9,  8,  8,  5,  5,  6,  1,  9, 10,  3,  6,  2,  6, 10,
        3,  5,  4,  1,  4,  8,  8,  3,  6,  2,  8,  6, 10,  2,  3,  9,  6,
        1, 10,  4,  4,  4,  2,  8,  7,  4,  2,  8,  3,  7,  6, 10,  9, 10,
        5,  8,  9,  6, 10

In [167]:
a.size

1000

In [168]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [169]:
np.median(a)

5.0

In [170]:
np.sum(a)

5485

In [171]:
np.round(np.var(a), 2)

8.19

In [172]:
np.round(np.mean(a), 2)

5.48

In [173]:
np.round(np.std(a), 2)

2.86

In [174]:
np.max(a)

10

In [175]:
np.min(a)

1

In [176]:
z = np.random.randint(10, size=1000)

In [177]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [178]:
set(z)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [179]:
a = np.array([2, -3, 4, 5, 7, 0, 1, -1])

In [180]:
a.argmax()

4

In [181]:
a.argmin()

1

In [182]:
A = np.array([0, 1, 2, 3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [183]:
B = np.array([3, 2, 0, 1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [184]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [185]:
np.dot(A, B)

array([[0, 1],
       [6, 7]])

In [186]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [187]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [188]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [189]:
np.linalg.det(A)

-2.0

## 1.4. NumPy Indexing and Slicing

### Indexing and Slicing

In [190]:
a=np.array([0,1,2,3])
b=np.array([[0,1,2,3],
            [4,5,6,7],
            [8,9,10,11]])

In [191]:
a[0]

0

In [192]:
b[0]

array([0, 1, 2, 3])

In [193]:
b[0][1]

1

In [194]:
b[0,1]

1

In [195]:
a1=np.array([0,10,20,30,40,50])
a1[5]

50

In [196]:
a1[5]=70

In [197]:
a1

array([ 0, 10, 20, 30, 40, 70])

In [199]:
a1[[1,3,4]]

array([10, 30, 40])

In [201]:
a2=np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [202]:
a2[0,2]

30

In [204]:
a2[2,2]=95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [205]:
a2[1]

array([40, 50, 60])

In [206]:
a2[2]=np.array([45,55,65])
a2

array([[10, 20, 30],
       [40, 50, 60],
       [45, 55, 65]])

In [207]:
a2

array([[10, 20, 30],
       [40, 50, 60],
       [45, 55, 65]])

In [208]:
a2[[0,2],[0,1]]

array([10, 55])

In [209]:
a=np.array([1,2,3,4,5,6])

In [210]:
a[a>3]

array([4, 5, 6])

In [211]:
a[a%2==0]

array([2, 4, 6])

### Array Slicing

In [213]:
b1=np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [214]:
b1[:3]

array([ 0, 10, 20])

In [215]:
b1[2:]

array([20, 30, 40, 50])

In [216]:
arr2d=np.arange(1,10).reshape(3,3)

In [217]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [219]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [220]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [221]:
arr2d[1, :2]

array([4, 5])

In [222]:
arr2d[:2,2]

array([3, 6])

In [223]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [224]:
names=np.array(['Bob', 'Joe', 'Tom', 'Bob', 'Tom', 'Joe', 'Joe'])

In [225]:
names

array(['Bob', 'Joe', 'Tom', 'Bob', 'Tom', 'Joe', 'Joe'], dtype='<U3')

In [226]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [227]:
names[names=='Bob']

array(['Bob', 'Bob'], dtype='<U3')

### Fancy Indexing

In [228]:
np.empty((8,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [229]:
arr=np.empty((8,4))

In [230]:
for i in range(8):
    arr[i]=i

In [231]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [232]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [233]:
arr[[-3,-5]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.]])

In [234]:
arr2=np.arange(20)

In [235]:
arrMask=(arr2%5==0)

In [236]:
arr2[arrMask]

array([ 0,  5, 10, 15])

In [237]:
arr2>10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [238]:
arrMask2=(arr2>=10)

In [239]:
arr2[arrMask & arrMask2]

array([10, 15])

## 1.5. Array Transposition and Axis Swap

### Array Transposition

In [240]:
arr=np.arange(15).reshape((3,5))

In [241]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [242]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [243]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [244]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [245]:
arr=np.random.randn(6,3)

In [246]:
arr

array([[-0.89407486,  1.10451809,  0.64056623],
       [ 0.03732225, -0.92839598,  0.68226154],
       [ 1.20472236,  0.81747792,  0.3347011 ],
       [ 0.4642397 , -1.10524664,  0.71061568],
       [-0.19065097, -1.9590654 , -1.77359902],
       [-0.62354511, -1.20237059,  0.68045368]])

In [247]:
arr.T

array([[-0.89407486,  0.03732225,  1.20472236,  0.4642397 , -0.19065097,
        -0.62354511],
       [ 1.10451809, -0.92839598,  0.81747792, -1.10524664, -1.9590654 ,
        -1.20237059],
       [ 0.64056623,  0.68226154,  0.3347011 ,  0.71061568, -1.77359902,
         0.68045368]])

In [248]:
np.dot(arr.T, arr)

array([[2.89279357, 0.57279289, 0.09971207],
       [0.57279289, 9.25535186, 2.21875224],
       [0.09971207, 2.21875224, 5.10147607]])

In [249]:
arr_1=np.arange(12).reshape(3,4)

In [250]:
arr_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [251]:
arr_1.reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [252]:
arr_1.transpose((0,1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [253]:
arr_1.transpose((1,0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [254]:
arr=np.arange(16).reshape((2,2,4))

In [255]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [256]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [257]:
arr.transpose((0,1,2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [258]:
arr.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [259]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [260]:
help(arr.swapaxes)

Help on built-in function swapaxes:

swapaxes(...) method of numpy.ndarray instance
    a.swapaxes(axis1, axis2)
    
    Return a view of the array with `axis1` and `axis2` interchanged.
    
    Refer to `numpy.swapaxes` for full documentation.
    
    See Also
    --------
    numpy.swapaxes : equivalent function



In [261]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [264]:
arr.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])