# Clase 26: Redes Neuronales y Deep Learning
## Introducción a las Redes Neuronales y Deep Learning
1. ¿Qué es una Red Neuronal?

Una Red Neuronal Artificial (ANN) es un modelo inspirado en el cerebro humano, diseñado para reconocer patrones complejos en datos. Se compone de neuronas artificiales (también llamadas nodos o unidades) que están organizadas en capas:

- Capa de entrada: Recibe los datos.
- Capas ocultas: Procesan los datos mediante funciones matemáticas.
- Capa de salida: Proporciona el resultado final del modelo.

Cada neurona está conectada a otras, y las conexiones tienen pesos que ajustan cómo se transmiten los datos. El aprendizaje en una red neuronal implica ajustar estos pesos para que la red produzca resultados precisos.

## 2. ¿Qué es Deep Learning?
Deep Learning es un subconjunto de machine learning que utiliza redes neuronales profundas, es decir, redes con muchas capas ocultas. Estas capas adicionales permiten que los modelos aprendan representaciones jerárquicas de los datos, lo que es útil para tareas complejas como la clasificación de imágenes o el procesamiento de lenguaje natural.

## 3. ¿Cómo Funciona una Red Neuronal?
Cada neurona realiza una operación matemática llamada combinación lineal sobre las entradas, multiplicándolas por un peso y sumando un sesgo (bias). El resultado pasa a través de una función de activación, que decide si la neurona debe activarse o no.

Algunas funciones de activación comunes incluyen:

- ReLU (Rectified Linear Unit): Activa solo valores positivos.
- Sigmoid: Convierte valores en una probabilidad entre 0 y 1.
- Tanh: Escala valores entre -1 y 1.

El objetivo del entrenamiento es minimizar el error entre las predicciones de la red y los valores reales. Esto se logra mediante un proceso llamado backpropagation o retropropagación, que ajusta los pesos de la red a través de optimización, generalmente con el algoritmo de gradiente descendente.

## Introducción a TensorFlow
TensorFlow es una de las bibliotecas más populares para construir y entrenar modelos de deep learning. Te permite definir redes neuronales de manera eficiente y aprovechar el hardware de aceleración como las GPUs.

4. Instalación de TensorFlow
Para usar TensorFlow, primero se debe instalar con:

In [29]:
# !pip install tensorflow

Si necesitas una versión específica, puedes usar:


In [30]:
# !pip install tensorflow==[versión-deseada]

# Ejercicios con TF

In [31]:
# Importar TF
import tensorflow as tf

In [32]:
tf.__version__

'2.17.0'

### Formas de crear un tensor

In [33]:
# Primera estrategia para crear un tensor a través de un array de numpy

# Importar numpy
import numpy as np

# Vamos a modificar de 8 por defecto a 3 los decimales impresos en numpy
# Más información https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html

np.set_printoptions(precision=3)

In [34]:
# Vamos a crear dos tensores a base de un array de numpy y de una lista
a = np.array([1, 2, 3], dtype=np.int32) # Array numpy
b = [4, 5, 6] # Lista

t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [35]:
type(a)

numpy.ndarray

In [36]:
type(t_a)

tensorflow.python.framework.ops.EagerTensor

In [37]:
type(b)

list

In [38]:
type(t_b)

tensorflow.python.framework.ops.EagerTensor

In [39]:
# Verificar si el dato es un tensor
tf.is_tensor(a), tf.is_tensor(t_a)

(False, True)

In [40]:
# Crear un tensor con unos en un shape
t_ones = tf.ones((2, 3))

t_ones.shape

TensorShape([2, 3])

In [41]:
t_ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [42]:
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [43]:
# Crear un tensor usando tf.constant
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)

print(const_tensor)

tf.Tensor([1.2   5.    3.142], shape=(3,), dtype=float32)


In [44]:
# Crear tensor con tf.fill
# El primer parámetro es el shape y el segundo es el escalar
tf.fill((2, 3), 1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [45]:
# Crear tensor one hot
tf.one_hot([0, 1, 2], 4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

### Modificación de forma y tipo de dato de un tensor

In [46]:
# Originalmente nuestro tensor t_a
t_a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [47]:
# tf.cast cambiamos el tipo de dato del tensor
t_a_new = tf.cast(t_a, tf.int64)

print(t_a_new.dtype)

<dtype: 'int64'>


In [48]:
t_a_new

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [49]:
# random.uniform entrega un conjunto de valores random con una distribución uniforme
t = tf.random.uniform(shape=(3, 5))

print(t)
print("---"*45)

t_tr = tf.transpose(t)
print(t.shape, ' --> ', t_tr.shape)

tf.Tensor(
[[0.929 0.477 0.292 0.304 0.995]
 [0.692 0.429 0.582 0.394 0.939]
 [0.638 0.152 0.296 0.726 0.141]], shape=(3, 5), dtype=float32)
---------------------------------------------------------------------------------------------------------------------------------------
(3, 5)  -->  (5, 3)


In [50]:
t_tr

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.929, 0.692, 0.638],
       [0.477, 0.429, 0.152],
       [0.292, 0.582, 0.296],
       [0.304, 0.394, 0.726],
       [0.995, 0.939, 0.141]], dtype=float32)>

In [51]:
# Reshape un tensor
t = tf.zeros((30,)) #Creamos un tensor con ceros

t_reshpae = tf.reshape(t, shape=(5, 6)) # Luego cambiamos la shape

print(t_reshpae.shape)

(5, 6)


In [52]:
# Tensor con ceros
t

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [53]:
# El tensor con el nuevo shape
t_reshpae

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [54]:
t = tf.zeros((1, 2, 1, 4, 1)) # Creamos un tensor con ceros

In [55]:
t

<tf.Tensor: shape=(1, 2, 1, 4, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.]]]]], dtype=float32)>

In [56]:
# Usamos squeeze para remover el shape
t_sqz = tf.squeeze(t, axis=(2, 4))

print(t.shape, ' --> ', t_sqz.shape)

(1, 2, 1, 4, 1)  -->  (1, 2, 4)


In [57]:
t_sqz

<tf.Tensor: shape=(1, 2, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

#### Operaciones Aritméticas
- Suma: `tf.add(x, y)` o el operador `+`
- Resta: `tf.subtract(x, y)` o el operador `-`
- Multiplicación: `tf.multiply(x, y)` o el operador `*`
- División: `tf.divide(x, y)` o el operador `/`
- Exponente: `tf.pow(x, y)` o el operador `**`
- Módulo: `tf.math.mod(x, y)`
#### Operaciones de Álgebra Lineal
- Producto Punto (dot product): `tf.linalg.matmul(x, y)` o el operador `@`
- Transposición: `tf.transpose(x)`
- Inversa: `tf.linalg.inv(x)`
- Determinante: `tf.linalg.det(x)`
- Descomposición en valores singulares (SVD): `tf.linalg.svd(x)`
#### Operaciones de Reducción
- Suma a lo largo del eje: `tf.reduce_sum(x, axis)`
- Promedio a lo largo del eje: `tf.reduce_mean(x, axis)`
- Máximo a lo largo del eje: `tf.reduce_max(x, axis)`
- Mínimo a lo largo del eje: `tf.reduce_min(x, axis)`
#### Operaciones de Comparación
- Igualdad: `tf.equal(x, y)`
- Desigualdad: `tf.not_equal(x, y)`
- Mayor que: `tf.greater(x, y)`
- Menor que: `tf.less(x, y)`
#### Operaciones Lógicas
- AND lógico: `tf.logical_and(x, y)`
- OR lógico: `tf.logical_or(x, y)`
- NOT lógico: `tf.logical_not(x)`
#### Operaciones de Activación
- ReLU: `tf.nn.relu(x)`
- Sigmoid: `tf.nn.sigmoid(x)`
- Tanh: `tf.nn.tanh(x)`
- Softmax: `tf.nn.softmax(x)`
#### Operaciones de Manipulación de Tensores
- Redimensionar: `tf.reshape(x, shape)`
- Concatenar: `tf.concat([x, y], axis)`
- Dividir: `tf.split(x, num_or_size_splits, axis)`
#### Operaciones de Normalización
- Normalización Batch: `tf.keras.layers.BatchNormalization(x)`
- Normalización de Capa: `tf.keras.layers.LayerNormalization(x)`

In [59]:
tf.random.set_seed(1) # Semilla global

t1 = tf.random.uniform(shape=(5, 2),
                       minval=-1.0,
                       maxval=1.0)

t2 = tf.random.normal(shape=(5, 2),
                      mean=0.0,
                      stddev=1.0)

In [60]:
t1

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.67 ,  0.803],
       [ 0.262, -0.131],
       [-0.416,  0.285],
       [ 0.952, -0.13 ],
       [ 0.32 ,  0.21 ]], dtype=float32)>

In [61]:
t2

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.403, -1.088],
       [-0.063,  1.337],
       [ 0.712, -0.489],
       [-0.764, -1.037],
       [-1.252,  0.021]], dtype=float32)>

In [62]:
# Multiplicación
t3 = tf.multiply(t1, t2).numpy()
print(t3)

[[-0.27  -0.874]
 [-0.017 -0.175]
 [-0.296 -0.139]
 [-0.727  0.135]
 [-0.401  0.004]]


In [63]:
t4 = tf.math.reduce_mean(t1, axis=0) # Computes the mean of elements across dimensions of a tensor

print(t4)

tf.Tensor([0.09  0.207], shape=(2,), dtype=float32)


In [64]:
t5 = tf.linalg.matmul(t1, t2, transpose_b=True) # Multiplies matrix a by matrix b, producing a * b
# If transpose_b is True, b is transposed before multiplication

print(t5)

tf.Tensor(
[[-1.144  1.115 -0.87  -0.321  0.856]
 [ 0.248 -0.191  0.25  -0.064 -0.331]
 [-0.478  0.407 -0.436  0.022  0.527]
 [ 0.525 -0.234  0.741 -0.593 -1.194]
 [-0.099  0.26   0.125 -0.462 -0.396]], shape=(5, 5), dtype=float32)


In [65]:
t6 = tf.linalg.matmul(t1, t2, transpose_a=True)

print(t6)

tf.Tensor(
[[-1.711  0.302]
 [ 0.371 -1.049]], shape=(2, 2), dtype=float32)


In [66]:
norm_t1 = tf.norm(t1, ord=2, axis=1).numpy() # Computes the norm of vectors, matrices, and tensors

print(norm_t1)

[1.046 0.293 0.504 0.96  0.383]


In [67]:
# Podríamos hacer el mismo calculo anterior con numpy
np.sqrt(np.sum(np.square(t1), axis=1))

array([1.046, 0.293, 0.504, 0.96 , 0.383], dtype=float32)

In [68]:
# Podrmos usar @ para multiplicar tensores
t1 @ tf.transpose(t2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.144,  1.115, -0.87 , -0.321,  0.856],
       [ 0.248, -0.191,  0.25 , -0.064, -0.331],
       [-0.478,  0.407, -0.436,  0.022,  0.527],
       [ 0.525, -0.234,  0.741, -0.593, -1.194],
       [-0.099,  0.26 ,  0.125, -0.462, -0.396]], dtype=float32)>

In [69]:
# Split de tensores
tf.random.set_seed(1)

t = tf.random.uniform((6,))

print(t.numpy())

t_splits = tf.split(t, 3)

[item.numpy() for item in t_splits]

[0.165 0.901 0.631 0.435 0.292 0.643]


[array([0.165, 0.901], dtype=float32),
 array([0.631, 0.435], dtype=float32),
 array([0.292, 0.643], dtype=float32)]

In [70]:
# concatenar tensores
A = tf.ones((3,))
B = tf.zeros((2,))

C = tf.concat([A, B], axis=0)
print(C.numpy())

[1. 1. 1. 0. 0.]


In [71]:
A

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [72]:
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [73]:
# Stacks a list of rank-R tensors into one rank-(R+1) tensor
A = tf.ones((3,))
B = tf.zeros((3,))

S = tf.stack([A, B], axis=1)
print(S.numpy())

[[1. 0.]
 [1. 0.]
 [1. 0.]]


## Datasets con TensorFlow

#### Building TensorFlow dataset in a tensor


In [ ]:
a = [1.2, 3.4, 7.5, 4.1, 5.0, 1.0]

ds = tf.data.Dataset.from_tensor_slices(a)

print(ds)

### 5. Construcción de un Modelo en TensorFlow
TensorFlow te permite definir redes neuronales de forma flexible. Aquí te muestro cómo definir una red neuronal simple usando la API de alto nivel Keras, que está integrada en TensorFlow.

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Definir un modelo secuencial
model = models.Sequential()

# Añadir una capa de entrada
model.add(layers.Dense(64, activation='relu', input_shape=(100,)))

# Añadir capas ocultas
model.add(layers.Dense(64, activation='relu'))

# Añadir la capa de salida
model.add(layers.Dense(10, activation='softmax'))

# Compilar el modelo
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


### 6. Entrenamiento del Modelo
Una vez que el modelo está definido, se entrena usando un conjunto de datos. El siguiente código entrena el modelo con datos de entrenamiento:

In [ ]:
# Asumiendo que tienes los datos de entrenamiento en X_train y y_train
model.fit(X_train, y_train, epochs=10, batch_size=32)


El modelo se entrena ajustando los pesos en cada iteración para minimizar la función de pérdida. Aquí, el modelo está usando la función de pérdida de categorical_crossentropy porque estamos clasificando en múltiples categorías.

### 7. Evaluación del Modelo
Después del entrenamiento, es importante evaluar el modelo con un conjunto de datos de prueba para ver su desempeño en datos no vistos:

In [ ]:
# Evaluar el modelo
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test accuracy: {accuracy}")