# Clase 26: Redes Neuronales y Deep Learning
## Introducción a las Redes Neuronales y Deep Learning
1. ¿Qué es una Red Neuronal?

Una Red Neuronal Artificial (ANN) es un modelo inspirado en el cerebro humano, diseñado para reconocer patrones complejos en datos. Se compone de neuronas artificiales (también llamadas nodos o unidades) que están organizadas en capas:

- Capa de entrada: Recibe los datos.
- Capas ocultas: Procesan los datos mediante funciones matemáticas.
- Capa de salida: Proporciona el resultado final del modelo.

Cada neurona está conectada a otras, y las conexiones tienen pesos que ajustan cómo se transmiten los datos. El aprendizaje en una red neuronal implica ajustar estos pesos para que la red produzca resultados precisos.

## 2. ¿Qué es Deep Learning?
Deep Learning es un subconjunto de machine learning que utiliza redes neuronales profundas, es decir, redes con muchas capas ocultas. Estas capas adicionales permiten que los modelos aprendan representaciones jerárquicas de los datos, lo que es útil para tareas complejas como la clasificación de imágenes o el procesamiento de lenguaje natural.

## 3. ¿Cómo Funciona una Red Neuronal?
Cada neurona realiza una operación matemática llamada combinación lineal sobre las entradas, multiplicándolas por un peso y sumando un sesgo (bias). El resultado pasa a través de una función de activación, que decide si la neurona debe activarse o no.

Algunas funciones de activación comunes incluyen:

- ReLU (Rectified Linear Unit): Activa solo valores positivos.
- Sigmoid: Convierte valores en una probabilidad entre 0 y 1.
- Tanh: Escala valores entre -1 y 1.

El objetivo del entrenamiento es minimizar el error entre las predicciones de la red y los valores reales. Esto se logra mediante un proceso llamado backpropagation o retropropagación, que ajusta los pesos de la red a través de optimización, generalmente con el algoritmo de gradiente descendente.

## Introducción a TensorFlow
TensorFlow es una de las bibliotecas más populares para construir y entrenar modelos de deep learning. Te permite definir redes neuronales de manera eficiente y aprovechar el hardware de aceleración como las GPUs.

4. Instalación de TensorFlow
Para usar TensorFlow, primero se debe instalar con:

In [ ]:
#!pip install tensorflow

Si necesitas una versión específica, puedes usar:


In [ ]:
#!pip install tensorflow==[versión-deseada]

### Verificar versión instalada

In [2]:
import tensorflow as tf
tf.__version__

'2.17.0'

In [3]:
import numpy as np

In [4]:
np.set_printoptions(precision=3)

In [5]:
a = np.array([1, 2, 3], dtype=np.int32)
b = [4, 5, 6]

t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [6]:
tf.is_tensor(a), tf.is_tensor(t_a)

(False, True)

In [7]:
type(a)

numpy.ndarray

In [8]:
type(t_a)

tensorflow.python.framework.ops.EagerTensor

In [9]:
t_ones = tf.ones((2, 3))

t_ones.shape

TensorShape([2, 3])

In [10]:
t_ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [12]:
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)

print(const_tensor)

tf.Tensor([1.2   5.    3.142], shape=(3,), dtype=float32)


In [13]:
tf.fill((2, 3), 1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [14]:
tf.one_hot([0, 1, 2], 4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [15]:
t_a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [16]:
t_a_new = tf.cast(t_a, tf.int64)

print(t_a_new.dtype)

<dtype: 'int64'>


In [17]:
t_a_new

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [18]:
t = tf.random.uniform(shape=(3, 5))

print(t)

tf.Tensor(
[[0.148 0.656 0.954 0.519 0.293]
 [0.602 0.228 0.693 0.08  0.928]
 [0.485 0.828 0.469 0.312 0.604]], shape=(3, 5), dtype=float32)


In [19]:
t_tr = tf.transpose(t)
print(t.shape, ' --> ', t_tr.shape)

(3, 5)  -->  (5, 3)


In [20]:
t_tr

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.148, 0.602, 0.485],
       [0.656, 0.228, 0.828],
       [0.954, 0.693, 0.469],
       [0.519, 0.08 , 0.312],
       [0.293, 0.928, 0.604]], dtype=float32)>

In [21]:
t = tf.zeros((30,))

print(t)

tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.], shape=(30,), dtype=float32)


In [22]:
t_reshpae = tf.reshape(t, shape=(5, 6))

In [23]:
print(t_reshpae)

tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(5, 6), dtype=float32)


In [24]:
print(t_reshpae.shape)

(5, 6)


In [28]:
t = tf.zeros((1, 2, 1, 4, 1))
print(t.shape)
print("----"*5)
print(t)

(1, 2, 1, 4, 1)
--------------------
tf.Tensor(
[[[[[0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]]]]], shape=(1, 2, 1, 4, 1), dtype=float32)


In [29]:
t_sqz = tf.squeeze(t, axis=(2, 4))

print(t.shape, ' --> ', t_sqz.shape)

(1, 2, 1, 4, 1)  -->  (1, 2, 4)


In [30]:
t_sqz

<tf.Tensor: shape=(1, 2, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [31]:
tf.random.set_seed(1)

t1 = tf.random.uniform(shape=(5, 2),
                       minval=-1.0,
                       maxval=1.0)

t2 = tf.random.normal(shape=(5, 2),
                      mean=0.0,
                      stddev=1.0)

In [32]:
t1

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.67 ,  0.803],
       [ 0.262, -0.131],
       [-0.416,  0.285],
       [ 0.952, -0.13 ],
       [ 0.32 ,  0.21 ]], dtype=float32)>

In [33]:
t2

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.403, -1.088],
       [-0.063,  1.337],
       [ 0.712, -0.489],
       [-0.764, -1.037],
       [-1.252,  0.021]], dtype=float32)>

In [34]:
t3 = tf.multiply(t1, t2).numpy()
print(t3)

[[-0.27  -0.874]
 [-0.017 -0.175]
 [-0.296 -0.139]
 [-0.727  0.135]
 [-0.401  0.004]]


In [ ]:
t4 = tf.math.reduce_mean(t1, axis=0)

print(t4)

### 5. Construcción de un Modelo en TensorFlow
TensorFlow te permite definir redes neuronales de forma flexible. Aquí te muestro cómo definir una red neuronal simple usando la API de alto nivel Keras, que está integrada en TensorFlow.

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Definir un modelo secuencial
model = models.Sequential()

# Añadir una capa de entrada
model.add(layers.Dense(64, activation='relu', input_shape=(100,)))

# Añadir capas ocultas
model.add(layers.Dense(64, activation='relu'))

# Añadir la capa de salida
model.add(layers.Dense(10, activation='softmax'))

# Compilar el modelo
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


### 6. Entrenamiento del Modelo
Una vez que el modelo está definido, se entrena usando un conjunto de datos. El siguiente código entrena el modelo con datos de entrenamiento:

In [ ]:
# Asumiendo que tienes los datos de entrenamiento en X_train y y_train
model.fit(X_train, y_train, epochs=10, batch_size=32)


El modelo se entrena ajustando los pesos en cada iteración para minimizar la función de pérdida. Aquí, el modelo está usando la función de pérdida de categorical_crossentropy porque estamos clasificando en múltiples categorías.

### 7. Evaluación del Modelo
Después del entrenamiento, es importante evaluar el modelo con un conjunto de datos de prueba para ver su desempeño en datos no vistos:

In [ ]:
# Evaluar el modelo
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test accuracy: {accuracy}")